networks:
  monitoring:
    driver: bridge

services:
  bible-bot:
    build: ../bible-bot/
    container_name: bible-bot
    volumes:
      - ../bible-bot/data/:/app/data
    env_file:
      - ../bible-bot/.env
    restart: unless-stopped

  # mtg-pipeline:
  #  build: ../mtg/
  #  container_name: mtg-pipeline
  #  volumes:
  #    - ../mtg/database:/app/database
  #    - ../mtg/src/dbt_project/profiles.yml:/home/botuser/.dbt/profiles.yml
  #  env_file:
  #    - ../mtg/.env

  # Monitoring Stack
  victoria-metrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoria-metrics
    command:
      - "--promscrape.config=/etc/victoria-metrics/scrape.yaml"
    volumes:
      - victoria_data:/victoria-metrics-data
      - ./victoria-metrics/scrape.yaml:/etc/victoria-metrics/scrape.yaml:ro
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    command:
      - "--web.listen-address=:9100"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=https://tiny.lab/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - victoria-metrics
    networks:
      - monitoring

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy:/etc/caddy
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - monitoring
    restart: unless-stopped

volumes:
  victoria_data:
  grafana_data:
  caddy_data:
  caddy_config:
